### ISSUE TITLE
Script breaks in 2.90 with 'keyword "apply_as" unrecognized'

### ISSUE THREAD

**Issue by SorayaProtera** [Cardboy0/Cardboy0s-SACS#4]
Blender version: 2.90, Steam release
SACS version: 1.53.2

Using the same model as in your quick-start example, and following the instructions in the Google Document, I tried to run the script, and got this as the full console output:

```##########################################################################
script "Softbodies with animation/shapekeys calculation begin"
##########################################################################
easy_mode = True    => Peparing your scene...
    ... doing some stuff
Dependency cycle detected:
  OBtifa_rig/DEF-pussy.L.001/BONE_CONSTRAINTS() depends on
  OBtifa_rig/DEF-pussy.L/BONE_DONE() via 'Damped Track'
  OBtifa_rig/DEF-pussy.L/BONE_READY() via 'Ready -> Done'
  OBtifa_rig/DEF-pussy.L/BONE_CONSTRAINTS() via 'Constraints -> Ready'
  OBtifa_rig/DEF-pussy.L/BONE_POSE_PARENT() via 'Pose -> Constraints Stack'
  OBtifa_rig/DEF-pussy.L.001/BONE_DONE() via 'Parent Bone -> Child Bone'
  OBtifa_rig/DEF-pussy.L.001/BONE_READY() via 'Ready -> Done'
  OBtifa_rig/DEF-pussy.L.001/BONE_CONSTRAINTS() via 'Constraints -> Ready'
Dependency cycle detected:
  OBtifa_rig/DEF-pussy.L.002/BONE_CONSTRAINTS() depends on
  OBtifa_rig/DEF-pussy.L.001/BONE_DONE() via 'Damped Track'
  OBtifa_rig/DEF-pussy.L.001/BONE_READY() via 'Ready -> Done'
  OBtifa_rig/DEF-pussy.L.001/BONE_CONSTRAINTS() via 'Constraints -> Ready'
  OBtifa_rig/DEF-pussy.L.001/BONE_POSE_PARENT() via 'Pose -> Constraints Stack'
  OBtifa_rig/DEF-pussy.L.002/BONE_DONE() via 'Parent Bone -> Child Bone'
  OBtifa_rig/DEF-pussy.L.002/BONE_READY() via 'Ready -> Done'
  OBtifa_rig/DEF-pussy.L.002/BONE_CONSTRAINTS() via 'Constraints -> Ready'
Dependency cycle detected:
  OBtifa_rig/DEF-pussy.L.003/BONE_CONSTRAINTS() depends on
  OBtifa_rig/DEF-pussy.L.002/BONE_DONE() via 'Damped Track'
  OBtifa_rig/DEF-pussy.L.002/BONE_READY() via 'Ready -> Done'
  OBtifa_rig/DEF-pussy.L.002/BONE_CONSTRAINTS() via 'Constraints -> Ready'
  OBtifa_rig/DEF-pussy.L.002/BONE_POSE_PARENT() via 'Pose -> Constraints Stack'
  OBtifa_rig/DEF-pussy.L.003/BONE_DONE() via 'Parent Bone -> Child Bone'
  OBtifa_rig/DEF-pussy.L.003/BONE_READY() via 'Ready -> Done'
  OBtifa_rig/DEF-pussy.L.003/BONE_CONSTRAINTS() via 'Constraints -> Ready'
Detected 3 dependency cycles
Dependency cycle detected:
  OBtifa_rig/DEF-pussy.L.001/BONE_CONSTRAINTS() depends on
  OBtifa_rig/DEF-pussy.L/BONE_DONE() via 'Damped Track'
  OBtifa_rig/DEF-pussy.L/BONE_READY() via 'Ready -> Done'
  OBtifa_rig/DEF-pussy.L/BONE_CONSTRAINTS() via 'Constraints -> Ready'
  OBtifa_rig/DEF-pussy.L/BONE_POSE_PARENT() via 'Pose -> Constraints Stack'
  OBtifa_rig/DEF-pussy.L.001/BONE_DONE() via 'Parent Bone -> Child Bone'
  OBtifa_rig/DEF-pussy.L.001/BONE_READY() via 'Ready -> Done'
  OBtifa_rig/DEF-pussy.L.001/BONE_CONSTRAINTS() via 'Constraints -> Ready'
Dependency cycle detected:
  OBtifa_rig/DEF-pussy.L.002/BONE_CONSTRAINTS() depends on
  OBtifa_rig/DEF-pussy.L.001/BONE_DONE() via 'Damped Track'
  OBtifa_rig/DEF-pussy.L.001/BONE_READY() via 'Ready -> Done'
  OBtifa_rig/DEF-pussy.L.001/BONE_CONSTRAINTS() via 'Constraints -> Ready'
  OBtifa_rig/DEF-pussy.L.001/BONE_POSE_PARENT() via 'Pose -> Constraints Stack'
  OBtifa_rig/DEF-pussy.L.002/BONE_DONE() via 'Parent Bone -> Child Bone'
  OBtifa_rig/DEF-pussy.L.002/BONE_READY() via 'Ready -> Done'
  OBtifa_rig/DEF-pussy.L.002/BONE_CONSTRAINTS() via 'Constraints -> Ready'
Dependency cycle detected:
  OBtifa_rig/DEF-pussy.L.003/BONE_CONSTRAINTS() depends on
  OBtifa_rig/DEF-pussy.L.002/BONE_DONE() via 'Damped Track'
  OBtifa_rig/DEF-pussy.L.002/BONE_READY() via 'Ready -> Done'
  OBtifa_rig/DEF-pussy.L.002/BONE_CONSTRAINTS() via 'Constraints -> Ready'
  OBtifa_rig/DEF-pussy.L.002/BONE_POSE_PARENT() via 'Pose -> Constraints Stack'
  OBtifa_rig/DEF-pussy.L.003/BONE_DONE() via 'Parent Bone -> Child Bone'
  OBtifa_rig/DEF-pussy.L.003/BONE_READY() via 'Ready -> Done'
  OBtifa_rig/DEF-pussy.L.003/BONE_CONSTRAINTS() via 'Constraints -> Ready'
Detected 3 dependency cycles
Dependency cycle detected:
  OBtifa_rig/DEF-pussy.L.001/BONE_CONSTRAINTS() depends on
  OBtifa_rig/DEF-pussy.L/BONE_DONE() via 'Damped Track'
  OBtifa_rig/DEF-pussy.L/BONE_READY() via 'Ready -> Done'
  OBtifa_rig/DEF-pussy.L/BONE_CONSTRAINTS() via 'Constraints -> Ready'
  OBtifa_rig/DEF-pussy.L/BONE_POSE_PARENT() via 'Pose -> Constraints Stack'
  OBtifa_rig/DEF-pussy.L.001/BONE_DONE() via 'Parent Bone -> Child Bone'
  OBtifa_rig/DEF-pussy.L.001/BONE_READY() via 'Ready -> Done'
  OBtifa_rig/DEF-pussy.L.001/BONE_CONSTRAINTS() via 'Constraints -> Ready'
Dependency cycle detected:
  OBtifa_rig/DEF-pussy.L.002/BONE_CONSTRAINTS() depends on
  OBtifa_rig/DEF-pussy.L.001/BONE_DONE() via 'Damped Track'
  OBtifa_rig/DEF-pussy.L.001/BONE_READY() via 'Ready -> Done'
  OBtifa_rig/DEF-pussy.L.001/BONE_CONSTRAINTS() via 'Constraints -> Ready'
  OBtifa_rig/DEF-pussy.L.001/BONE_POSE_PARENT() via 'Pose -> Constraints Stack'
  OBtifa_rig/DEF-pussy.L.002/BONE_DONE() via 'Parent Bone -> Child Bone'
  OBtifa_rig/DEF-pussy.L.002/BONE_READY() via 'Ready -> Done'
  OBtifa_rig/DEF-pussy.L.002/BONE_CONSTRAINTS() via 'Constraints -> Ready'
Dependency cycle detected:
  OBtifa_rig/DEF-pussy.L.003/BONE_CONSTRAINTS() depends on
  OBtifa_rig/DEF-pussy.L.002/BONE_DONE() via 'Damped Track'
  OBtifa_rig/DEF-pussy.L.002/BONE_READY() via 'Ready -> Done'
  OBtifa_rig/DEF-pussy.L.002/BONE_CONSTRAINTS() via 'Constraints -> Ready'
  OBtifa_rig/DEF-pussy.L.002/BONE_POSE_PARENT() via 'Pose -> Constraints Stack'
  OBtifa_rig/DEF-pussy.L.003/BONE_DONE() via 'Parent Bone -> Child Bone'
  OBtifa_rig/DEF-pussy.L.003/BONE_READY() via 'Ready -> Done'
  OBtifa_rig/DEF-pussy.L.003/BONE_CONSTRAINTS() via 'Constraints -> Ready'
Detected 3 dependency cycles
    ... Converting your objects with the .mdd Format
Dependency cycle detected:
  OBtifa_rig/DEF-pussy.L.001/BONE_CONSTRAINTS() depends on
  OBtifa_rig/DEF-pussy.L/BONE_DONE() via 'Damped Track'
  OBtifa_rig/DEF-pussy.L/BONE_READY() via 'Ready -> Done'
  OBtifa_rig/DEF-pussy.L/BONE_CONSTRAINTS() via 'Constraints -> Ready'
  OBtifa_rig/DEF-pussy.L/BONE_POSE_PARENT() via 'Pose -> Constraints Stack'
  OBtifa_rig/DEF-pussy.L.001/BONE_DONE() via 'Parent Bone -> Child Bone'
  OBtifa_rig/DEF-pussy.L.001/BONE_READY() via 'Ready -> Done'
  OBtifa_rig/DEF-pussy.L.001/BONE_CONSTRAINTS() via 'Constraints -> Ready'
Dependency cycle detected:
  OBtifa_rig/DEF-pussy.L.002/BONE_CONSTRAINTS() depends on
  OBtifa_rig/DEF-pussy.L.001/BONE_DONE() via 'Damped Track'
  OBtifa_rig/DEF-pussy.L.001/BONE_READY() via 'Ready -> Done'
  OBtifa_rig/DEF-pussy.L.001/BONE_CONSTRAINTS() via 'Constraints -> Ready'
  OBtifa_rig/DEF-pussy.L.001/BONE_POSE_PARENT() via 'Pose -> Constraints Stack'
  OBtifa_rig/DEF-pussy.L.002/BONE_DONE() via 'Parent Bone -> Child Bone'
  OBtifa_rig/DEF-pussy.L.002/BONE_READY() via 'Ready -> Done'
  OBtifa_rig/DEF-pussy.L.002/BONE_CONSTRAINTS() via 'Constraints -> Ready'
Dependency cycle detected:
  OBtifa_rig/DEF-pussy.L.003/BONE_CONSTRAINTS() depends on
  OBtifa_rig/DEF-pussy.L.002/BONE_DONE() via 'Damped Track'
  OBtifa_rig/DEF-pussy.L.002/BONE_READY() via 'Ready -> Done'
  OBtifa_rig/DEF-pussy.L.002/BONE_CONSTRAINTS() via 'Constraints -> Ready'
  OBtifa_rig/DEF-pussy.L.002/BONE_POSE_PARENT() via 'Pose -> Constraints Stack'
  OBtifa_rig/DEF-pussy.L.003/BONE_DONE() via 'Parent Bone -> Child Bone'
  OBtifa_rig/DEF-pussy.L.003/BONE_READY() via 'Ready -> Done'
  OBtifa_rig/DEF-pussy.L.003/BONE_CONSTRAINTS() via 'Constraints -> Ready'
Detected 3 dependency cycles
Dependency cycle detected:
  OBtifa_rig/DEF-pussy.L.001/BONE_CONSTRAINTS() depends on
  OBtifa_rig/DEF-pussy.L/BONE_DONE() via 'Damped Track'
  OBtifa_rig/DEF-pussy.L/BONE_READY() via 'Ready -> Done'
  OBtifa_rig/DEF-pussy.L/BONE_CONSTRAINTS() via 'Constraints -> Ready'
  OBtifa_rig/DEF-pussy.L/BONE_POSE_PARENT() via 'Pose -> Constraints Stack'
  OBtifa_rig/DEF-pussy.L.001/BONE_DONE() via 'Parent Bone -> Child Bone'
  OBtifa_rig/DEF-pussy.L.001/BONE_READY() via 'Ready -> Done'
  OBtifa_rig/DEF-pussy.L.001/BONE_CONSTRAINTS() via 'Constraints -> Ready'
Dependency cycle detected:
  OBtifa_rig/DEF-pussy.L.002/BONE_CONSTRAINTS() depends on
  OBtifa_rig/DEF-pussy.L.001/BONE_DONE() via 'Damped Track'
  OBtifa_rig/DEF-pussy.L.001/BONE_READY() via 'Ready -> Done'
  OBtifa_rig/DEF-pussy.L.001/BONE_CONSTRAINTS() via 'Constraints -> Ready'
  OBtifa_rig/DEF-pussy.L.001/BONE_POSE_PARENT() via 'Pose -> Constraints Stack'
  OBtifa_rig/DEF-pussy.L.002/BONE_DONE() via 'Parent Bone -> Child Bone'
  OBtifa_rig/DEF-pussy.L.002/BONE_READY() via 'Ready -> Done'
  OBtifa_rig/DEF-pussy.L.002/BONE_CONSTRAINTS() via 'Constraints -> Ready'
Dependency cycle detected:
  OBtifa_rig/DEF-pussy.L.003/BONE_CONSTRAINTS() depends on
  OBtifa_rig/DEF-pussy.L.002/BONE_DONE() via 'Damped Track'
  OBtifa_rig/DEF-pussy.L.002/BONE_READY() via 'Ready -> Done'
  OBtifa_rig/DEF-pussy.L.002/BONE_CONSTRAINTS() via 'Constraints -> Ready'
  OBtifa_rig/DEF-pussy.L.002/BONE_POSE_PARENT() via 'Pose -> Constraints Stack'
  OBtifa_rig/DEF-pussy.L.003/BONE_DONE() via 'Parent Bone -> Child Bone'
  OBtifa_rig/DEF-pussy.L.003/BONE_READY() via 'Ready -> Done'
  OBtifa_rig/DEF-pussy.L.003/BONE_CONSTRAINTS() via 'Constraints -> Ready'
Detected 3 dependency cycles
Traceback (most recent call last):
  File "D:\Libraries\Documents\Blender\My Projects\First Belly Bulge\bellybulge.blend\SACS V_01_53_2.py", line 655, in <module>
  File "D:\Libraries\Documents\Blender\My Projects\First Belly Bulge\bellybulge.blend\SACS V_01_53_2.py", line 217, in apply_modifiers
  File "C:\Games\Steam\steamapps\common\Blender\2.90\scripts\modules\bpy\ops.py", line 199, in __call__
    ret = op_call(self.idname_py(), C_dict, kw, C_exec, C_undo)
TypeError: Converting py args to operator properties: : keyword "apply_as" unrecognized
Error: Python script failed, check the message in the system console

**Comment by Cardboy0** [comment]
Yes you're right, i took a break so I didn't notice anything when Blender updated until I got active again. Version 1.53.2.1 fixes that, literally just deleted the apply_as="DATA" parts.
Thanks for telling me though!
